@extends('layouts.public')

@section('title', 'Services | Physical Therapy Services Eugene')
@section('description', 'Explore physical therapy, massage therapy, manual therapy, STOTT Pilates, Graston Technique, lymphedema therapy, orthopedic rehab, sports rehab, oncology rehab, and personalized treatment programs.')
@section('canonical', 'https://www.ptsclinic.com/services')
@section('og_title', 'PTS Services')
@section('og_description', 'Evidence-based therapy and rehabilitation services in Eugene, Oregon.')
@section('active', 'services')

@section('head')
<script type="application/ld+json">
  {"@@context":"https://schema.org","@@type":"FAQPage","mainEntity":[{"@@type":"Question","name":"Do I need a referral for physical therapy?","acceptedAnswer":{"@@type":"Answer","text":"Referral requirements depend on your insurance plan and condition. Call Physical Therapy Services so the team can help verify next steps."}},{"@@type":"Question","name":"What should I expect during treatment?","acceptedAnswer":{"@@type":"Answer","text":"Your first visit includes an evaluation, movement and pain assessment, goals, and a personalized treatment plan."}},{"@@type":"Question","name":"Does PTS offer massage therapy?","acceptedAnswer":{"@@type":"Answer","text":"Yes. Massage therapy is available as part of treatment when appropriate and as a self-pay option for current patients and the public."}}]}
  </script>
@endsection

@section('content')
<section class="page-hero"><div class="container reveal"><p class="eyebrow">Services</p><h1>Scientifically validated, evidence-based treatments.</h1><p>We at Physical Therapy Services use a variety of different techniques and modalities such as manual therapy, Stott Pilates, and Graston Technique.</p></div></section>

    <section class="section">
      <div class="container">
        <div class="section-heading reveal"><p class="eyebrow">Treatment menu</p><h2>Every service includes assessment, treatment, home guidance, and progress checks.</h2></div>
        <div class="grid grid-2">
          <article class="card card-pad service-card reveal" id="physical-therapy"><span class="icon">PT</span><h2>Physical Therapy</h2><p>It is a health care profession that provides treatment to individuals to develop, maintain and restore maximum movement and function throughout life. This includes providing treatment in circumstances where movement and function are threatened by aging, injury, or disease.</p><p>Physical therapy is concerned with identifying and maximizing quality of life and movement potential within the spheres of promotion, prevention, treatment/intervention, and rehabilitation.</p><a href="contact.html">Ask about physical therapy</a></article>
          <article class="card card-pad service-card reveal" id="massage-therapy"><span class="icon">MT</span><h2>Massage Therapy</h2><p>Massage therapy can be very effective in helping with injury, muscle tightness, and overall pain. We at PTS include manual therapy in your treatment when we feel it is necessary.</p><p>There is also a self pay massage therapy option for the public as well as current patients.</p><a href="massage-therapy.html">View massage pricing</a></article>
          <article class="card card-pad service-card reveal" id="manual-therapy"><span class="icon">MA</span><h2>Manual Therapy</h2><p>We at Physical Therapy Services use a variety of different techniques and modalities such as manual therapy, Stott Pilates, and Graston Technique.</p><a href="contact.html">Ask about manual therapy</a></article>
          <article class="card card-pad service-card reveal" id="stott-pilates"><span class="icon">SP</span><h2>STOTT Pilates</h2><p>We at Physical Therapy Services use a variety of different techniques and modalities such as manual therapy, Stott Pilates, and Graston Technique.</p><a href="contact.html">Ask about Pilates therapy</a></article>
          <article class="card card-pad service-card reveal" id="graston-technique"><span class="icon">GT</span><h2>Graston Technique</h2><p>We at Physical Therapy Services use a variety of different techniques and modalities such as manual therapy, Stott Pilates, and Graston Technique.</p><a href="contact.html">Ask about Graston</a></article>
          <article class="card card-pad service-card reveal" id="lymphedema-therapy"><span class="icon">LT</span><h2>Lymphedema Therapy</h2><p>Lymphedema is the accumulation of lymphatic fluid in one or more parts of the body due to the lymph load exceeding the ability of the lymphatic system to adequately drain lymphatic fluid. This may result from damage to the lymphatic system, an overproduction of lymphatic fluid, or a combination of both.</p><p>Treatment for lymphedema is important for the following reasons:</p><ul class="check-list"><li>To improve symptom relief of tightness, heaviness and discomfort.</li><li>To prevent progression of hardening of the tissue and skin.</li><li>To reduce chance of infection and the development of wounds.</li><li>To promote wound healing.</li><li>To improve skin health.</li><li>To reduce the need for more extensive treatments in the future.</li></ul><p>Physical Therapy Services treats lymphedema with the goal of reducing swelling, improving health, and improving quality of life through education and treatments regarding the importance of skin care, therapeutic exercise, manual lymphatic drainage, and appropriate compression.</p><p>We treat lymphedema secondary to conditions such as lipedema, cancer, trauma, venous insufficiency, injury, and surgery.</p><a href="contact.html">Ask about lymphedema care</a></article>
          <article class="card card-pad service-card reveal" id="orthopedic-rehabilitation"><span class="icon">OR</span><h2>Orthopedic Rehabilitation</h2><p><strong>Description:</strong> Recovery care for joints, muscles, spine, postural issues, and post-surgical needs.</p><p><strong>Benefits:</strong> Strength, flexibility, joint confidence, and safer return to daily activities.</p><p><strong>Process:</strong> Diagnosis-specific exam, exercise progression, manual therapy, and outcome tracking.</p><a href="contact.html">Ask about orthopedic rehab</a></article>
          <article class="card card-pad service-card reveal" id="sports-rehabilitation"><span class="icon">SR</span><h2>Sports Rehabilitation</h2><p><strong>Description:</strong> Rehab for athletes and active people returning to training, play, and recreation.</p><p><strong>Benefits:</strong> Safer return to sport, improved mechanics, conditioning, and injury-risk reduction.</p><p><strong>Process:</strong> Sport demands review, strength and agility progressions, and return-to-activity testing.</p><a href="contact.html">Ask about sports rehab</a></article>
          <article class="card card-pad service-card reveal" id="oncology-rehabilitation"><span class="icon">ON</span><h2>Oncology Physical Therapy</h2><p>Physical therapy can help restore mobility, reduce pain, improve energy, and improve quality of life for those experiencing effects from cancer and cancer treatment.</p><p>If you are having trouble with activities related to your life due to pain, loss of mobility, muscle weakness, swelling, or need a better understanding of your own cancer experience, Physical Therapy Services can help.</p><p>At Physical Therapy Services we provide specialized care for individuals experiencing side effects from cancer treatment, including pain management, reduced mobility following surgery, fatigue related to chemotherapy and radiation, muscle weakness from chemotherapy, post-surgical cording restrictions, radiation induced pain and mobility limitations, chemotherapy induced neuropathy, and lymphedema.</p><a href="contact.html">Ask about oncology physical therapy</a></article>
          <article class="card card-pad service-card reveal" id="personalized-treatment"><span class="icon">1:1</span><h2>Personalized Treatment Programs</h2><p><strong>Description:</strong> Custom plans designed individually for each patient and condition.</p><p><strong>Benefits:</strong> Clear goals, practical home care, efficient visits, and a plan that adapts over time.</p><p><strong>Process:</strong> Intake, evaluation, goals, treatment, reassessment, and discharge planning.</p><a href="contact.html">Ask about custom plans</a></article>
        </div>
      </div>
    </section>

    <section class="section soft">
      <div class="container split">
        <div class="reveal"><p class="eyebrow">FAQ</p><h2>Common service questions.</h2><p>Call the clinic for insurance-specific answers, scheduling questions, and referral details.</p></div>
        <div class="accordion reveal" data-accordion>
          <button type="button" aria-expanded="false">Do I need a referral?</button><div class="panel"><div><p>Referral rules vary by insurance and diagnosis. PTS can help you understand what your plan requires.</p></div></div>
          <button type="button" aria-expanded="false">What happens during the first visit?</button><div class="panel"><div><p>Your therapist reviews your history, tests movement and pain, explains findings, and starts a treatment plan.</p></div></div>
          <button type="button" aria-expanded="false">Can I book massage without being a therapy patient?</button><div class="panel"><div><p>Yes. PTS offers self-pay massage therapy options for the public as well as current patients.</p></div></div>
          <button type="button" aria-expanded="false">How long will therapy take?</button><div class="panel"><div><p>The recommended frequency depends on your evaluation, condition, goals, and insurance requirements.</p></div></div>
        </div>
      </div>
    </section>
    <section class="cta-band"><div class="container cta-inner reveal"><div><h2>Not sure which service fits?</h2><p>Call PTS and the team will help you choose the right next step.</p></div><a class="btn btn-coral" href="tel:+15413457532">Call PTS</a></div></section>
@endsection
